### PR TITLE
Added missing ESM types export condition first

### LINKED ISSUE #173: Fix Typescript types resolution
The current `package.json` breaks TypeScript when used with `nodenext` (ESM) module resolution.
The `types` field in the `package.json` is no longer respected when using `exports` as this package does. See [this comment](https://github.com/microsoft/TypeScript/issues/48235#issuecomment-1067363731).

The recommended approach is to provide multiple type definition files, that should reside alongside the `js`-files, i.e.:
`./dist/esm/index.d.ts` and `./dist/cjs/index.d.cts`. The `types` field can be used as a fallback for older TS versions.

 If you have to provide a single types file, it should say instead: 

```js
 "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js"
    }
  },
```

This is explained here:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#package-json-exports-imports-and-self-referencing

### PR DESCRIPTION
**Pull request by jonaskello**
Fixes #173 

Supersedes #214 since types expression needs to come first.

### CODE REVIEW

**Comment by jonaskello** [comment]
This is a rather small change but a total blocker for using node16/nodenext module resolution in typescript. There is no workaround as according to the typescript team this should be [fixed by package maintainers](https://github.com/microsoft/TypeScript/issues/48235#issuecomment-1067363731):

> In short: if you encounter any package with a types package json entry but not types in a provided export map - report it as an issue on that package; they've (likely unintentionally) broken TS support.

@mike-marcacci Would it be possible to have this merged and released in an patch version?

**Comment by SirBernardPhilip** [comment]
I would need this fixed as well, I would appreciate this being released soon too.

**Comment by mogzol** [comment]
The workaround I did was to copy all the type definitions from `index.d.ts` in the redlock package into a `redlock.d.ts` file in my typings folder, wrapping them in a `declare module ...`:

```typescript
declare module "redlock" {
    // Types from node_modules/redlock/dist/index.d.ts go here, with the "declare" keywords removed

    import { EventEmitter } from "events";
    import { Redis as IORedisClient, Cluster as IORedisCluster } from "ioredis";
    type Client = IORedisClient | IORedisCluster;
    // ...
}
```

For that to work you also have to add your typings folder into the `typeRoots` property in your tsconfig:
```json
{
  "compilerOptions": {
    "typeRoots": ["./node_modules/@types", "./typings"],
  }
}
```

I would really appreciate this PR being merged and released soon, but at least in the meantime this works.

**Comment by jonaskello** [comment]
@mike-marcacci FYI this PR only adds a single line to package.json, so it should not be much work to review.

**Comment by binsonc** [comment]
Our project migration to esm is currently blocked on this, can we have this merged @mike-marcacci ?

Not in favor of having a copy of the declaration file within our project.

**Comment by ryan-gies-agilysys** [comment]
> @mike-marcacci FYI this PR only adds a single line to package.json, so it should not be much work to review.

Have been running with this change for months and can verify it is sound.

**Review by ryan-gies-agilysys — APPROVED** [review]

**Comment by CarsonF** [comment]
@mike-marcacci Can we get a release with this?

**Comment by joonaskaustel** [comment]
When is the release of this?

**Comment by raimoa1** [comment]
Does not seem to be a big change, could this be released soon please? Our esm transformation is put on hold because of one package :/

**Comment by dgg** [comment]
I cannot use this package in my typescript ESM project because this issue has not been released.

**Comment by nkeil** [comment]
Also waiting on this to be realeased.

In the meantime, you can use this in your `package.json` to use the ESM update:
```json
"dependencies": {
  "redlock": "git+https://github.com/mike-marcacci/node-redlock.git"
}
```

**Comment by williamoverton** [comment]
Is this project abandoned? There seems to be no chance of an npm release anytime soon?

**Comment by filipforro** [comment]
@mike-marcacci Would it be possible to have this merged and released in a patch version (as others mentioned), thanks!

**Comment by CarsonF** [comment]
FWIW I switched to https://github.com/swarthy/redis-semaphore

**Comment by arvindell** [comment]
Hi, i am also affected by this. Could we get a new npm patch version?

**Comment by arvindell** [comment]
I ended up using the `pnpm patch` command to edit the package.json file:

https://pnpm.io/cli/patch

This results in a path file like this:

```
diff --git a/CHANGELOG.md b/CHANGELOG.md
deleted file mode 100644
index 8700963f5c9ec9fc1fdc53846846130bfc2f2108..0000000000000000000000000000000000000000
diff --git a/package.json b/package.json
index 606d1775fb0c11aab4918c50d20d72bce1684158..45e6d46410792ef273d7d2b2bc92cd5964a3eef5 100644
--- a/package.json
+++ b/package.json
@@ -15,6 +15,7 @@
   "types": "./dist/index.d.ts",
   "exports": {
     ".": {
+      "types": "./dist/index.d.ts",
       "import": "./dist/esm/index.js",
       "require": "./dist/cjs/index.js"
     }
```

**Pull request merged**
