### PR TITLE
v5

### PR DESCRIPTION
**Pull request by FauxFaux**
I've started work on my own `v5` branch, off your branch. Feel free to cherry-pick commits. I plan to rebase / edit history.

 * fix two bugs with passing arguments
 * fix one bug with retries
 * use jest locally by exposing the ports from docker-compose

### CODE REVIEW

**Comment by FauxFaux** [comment]
Haha, it's the one year anniversary of #70. This is a complete coincidence.

**Comment by FauxFaux** [comment]
With the larger test matrix there's occasional failures like this:

```
  ● ioredis, dbs: 2, resources: 1 › should extend an unexpired lock

    expect(received).toBeGreaterThan(expected)

    Expected: > 1619779881592
    Received:   1619779881592

      111 |       expect(four.expiration).toBeGreaterThan(Date.now() - 1);
      112 |       expect(four.attempts).toHaveLength(1);
    > 113 |       expect(four.expiration).toBeGreaterThan(threeExpires);
          |                               ^
      114 |     });
      115 |
      116 |     it("should fail after the maximum retry count is exceeded", async () => {

      at Object.<anonymous> (test/redlock.test.ts:113:31)
```

Seems to always be with multiple dbs. Is there a problem with `extend()`, or can anyone see anything wrong with the test?

**Comment by FauxFaux** [comment]
Maybe it takes literally zero millis to get between those two tests. A sleep helps.

**Comment by mike-marcacci** [comment]
@FauxFaux this is so incredibly helpful – thanks so much for all this effort! My current professional workload is currently well over my capacity, so I just haven't had the chance to give this project the attention it deserves. But as soon as I do find a chance to steal away for a couple hours, this is high on my list of things to knock out, and you just made it much easier for me :)

**Comment by MichielDeMey** [comment]
Nice to see some progress on the long awaited v5, should we rebase https://github.com/mike-marcacci/node-redlock/pull/70 to this branch as well?

**Comment by mike-marcacci** [comment]
Closing this, as many of these changes have already been incorporated into v5 (currently in beta). Thanks for the contributions!!

**Pull request closed without merging**
